Repository thoth-station/mi-scheduler, pull requests merged in 2020-11, with the labels that each got.

#52 Add francesco as approver
  OWNERS
Labels: approved, size/XS

#53 Automatic update of dependency thoth-common from 0.20.0 to 0.20.4
  Pipfile.lock
Labels: approved, bot, size/M

#51 Remove and use utitilies that are now in openshift.
  app.py
Labels: approved, size/S

#54 port to python 38
  .aicoe-ci.yaml
  Pipfile
  Pipfile.lock
Labels: approved, size/M

#55 update thoth yaml
  .thoth.yaml
Labels: approved, size/XS

#56 update .aicoe-ci.yaml
  .aicoe-ci.yaml
Labels: approved, size/XS
