Repository thoth-station/mi-scheduler, pull requests merged in 2020-07, with the labels that each got.

#1 Add scheduler, configmap and pipfiles [8pt]
  .github/CODEOWNERS
  .github/PULL_REQUEST_TEMPLATE.md
  MANIFEST.in
  Pipfile
  Pipfile.lock
  README.rst
  app.py
  template/__init__.py
  template/version.py
Labels: approved, size/L

#2 Expand logged messages lazily
  app.py
Labels: approved, size/XS

#3 Log workflow id to track actions
  app.py
Labels: approved, size/XS

#4 Assign Dominik to review PRs automatically
  .github/CODEOWNERS
  OWNERS
Labels: approved, size/S

#5 Automatic update of dependency thoth-common from 0.14.0 to 0.14.1
  Pipfile.lock
Labels: approved, bot, size/S

#10 README documentation and pre-commit configuration change
  .pre-commit-config.yaml
  OWNERS
  README.md
  README.rst
Labels: approved, size/M

#11 include aicoe-ci configuration file
  .aicoe-ci.yaml
  .coafile
  .zuul.yaml
Labels: approved, size/M

#13 Release of version 0.0.1
  CHANGELOG.md
  app.py
Labels: approved, bot, size/S

#16 Automatic update of dependency thoth-common from 0.14.1 to 0.14.2
  Pipfile.lock
Labels: approved, bot, size/S

#14 Remove CLI from mi-scheduler
  app.py
Labels: approved, size/M

#19 Release of version 1.0.0
  CHANGELOG.md
  app.py
Labels: approved, bot, size/XS

#21 Release of version 1.0.1
  CHANGELOG.md
  app.py
Labels: approved, bot, size/XS

#22 extract data from entire cm returned by get_configmap
  app.py
Labels: approved, size/XS

#24 Release of version 1.0.2
  CHANGELOG.md
  app.py
Labels: approved, bot, size/XS

#25 Secure empty string lists and add logger for CM
  app.py
Labels: approved, size/S

#28 Release of version 1.0.3
  CHANGELOG.md
  app.py
Labels: approved, bot, size/XS

#29 Rename to match method in thoth.common
  app.py
Labels: approved, size/XS

#33 Release of version 1.0.4
  CHANGELOG.md
  app.py
Labels: approved, bot, size/XS

#35 get token from env variable
  app.py
Labels: approved, size/XS

#37 Release of version 1.0.5
  CHANGELOG.md
  app.py
Labels: approved, bot, size/XS

#38 Rename submit_srcopsmetrics_workflow to mi
  app.py
Labels: approved, size/XS

#39 Automatic update of dependency thoth-common from 0.14.2 to 0.15.0
  Pipfile.lock
Labels: approved, bot

#41 Release of version 1.0.6
  CHANGELOG.md
  app.py
Labels: approved, bot, size/XS
